# Generated by Django 6.0.7 on 2026-07-14 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_image_post_remove_soundtrack_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', through='post.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
