# Generated by Django 6.0.7 on 2026-07-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_bookmark_updated_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundtrack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/soundtrack_images/'),
        ),
    ]
