# Generated by Django 6.0.7 on 2026-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_soundtrack_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundtrack',
            name='image',
        ),
        migrations.AlterField(
            model_name='soundtrack',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sound_tracks/'),
        ),
    ]
