# Generated by Django 6.0.7 on 2026-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_soundtrack_image_alter_soundtrack_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user/soundtracks/'),
        ),
    ]
